# Generated by Django 6.0.7 on 2026-09-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
